version: '3.5'

services:
  frontend:
    image: nginx
    volumes:
    - ./docker/nginx/services:/etc/nginx/conf.d/
    - ./:/var/www/html
    ports:
      - "80:80"

  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - ./docker/app/php-fpm/www.conf:/etc/php/7.4/fpm/pool.d/www.conf

  mysql.database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - ./var/database_data/mysql:/var/lib/mysql

  mongodb.database:
    image: mongo
    ports:
    - 27017:27017
    #- 27018:27018
    #- 27019:27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./docker/mongodb/mongod.conf:/etc/mongod.conf
      - ./var/database_data/mongo:/data/db
    command: ["-f", "/etc/mongod.conf"]

  cassandra.database:
    image: cassandra
    volumes:
      - ./var/database_data/cassandra:/var/lib/cassandra
    ports:
      - 9042:9042

